// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dataauth.proxies;

public class AkSk
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject akSkMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataAuth.AkSk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ak("Ak"),
		Sk("Sk"),
		EndDateTime("EndDateTime"),
		Enable("Enable"),
		AkSk_Group("DataAuth.AkSk_Group");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AkSk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AkSk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject akSkMendixObject)
	{
		if (akSkMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, akSkMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.akSkMendixObject = akSkMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AkSk.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dataauth.proxies.AkSk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dataauth.proxies.AkSk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dataauth.proxies.AkSk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dataauth.proxies.AkSk(context, mendixObject);
	}

	public static dataauth.proxies.AkSk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dataauth.proxies.AkSk.initialize(context, mendixObject);
	}

	public static java.util.List<dataauth.proxies.AkSk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> dataauth.proxies.AkSk.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ak
	 */
	public final java.lang.String getAk()
	{
		return getAk(getContext());
	}

	/**
	 * @param context
	 * @return value of Ak
	 */
	public final java.lang.String getAk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ak.toString());
	}

	/**
	 * Set value of Ak
	 * @param ak
	 */
	public final void setAk(java.lang.String ak)
	{
		setAk(getContext(), ak);
	}

	/**
	 * Set value of Ak
	 * @param context
	 * @param ak
	 */
	public final void setAk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ak)
	{
		getMendixObject().setValue(context, MemberNames.Ak.toString(), ak);
	}

	/**
	 * @return value of Sk
	 */
	public final java.lang.String getSk()
	{
		return getSk(getContext());
	}

	/**
	 * @param context
	 * @return value of Sk
	 */
	public final java.lang.String getSk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sk.toString());
	}

	/**
	 * Set value of Sk
	 * @param sk
	 */
	public final void setSk(java.lang.String sk)
	{
		setSk(getContext(), sk);
	}

	/**
	 * Set value of Sk
	 * @param context
	 * @param sk
	 */
	public final void setSk(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sk)
	{
		getMendixObject().setValue(context, MemberNames.Sk.toString(), sk);
	}

	/**
	 * @return value of EndDateTime
	 */
	public final java.util.Date getEndDateTime()
	{
		return getEndDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateTime
	 */
	public final java.util.Date getEndDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDateTime.toString());
	}

	/**
	 * Set value of EndDateTime
	 * @param enddatetime
	 */
	public final void setEndDateTime(java.util.Date enddatetime)
	{
		setEndDateTime(getContext(), enddatetime);
	}

	/**
	 * Set value of EndDateTime
	 * @param context
	 * @param enddatetime
	 */
	public final void setEndDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddatetime)
	{
		getMendixObject().setValue(context, MemberNames.EndDateTime.toString(), enddatetime);
	}

	/**
	 * @return value of Enable
	 */
	public final java.lang.Boolean getEnable()
	{
		return getEnable(getContext());
	}

	/**
	 * @param context
	 * @return value of Enable
	 */
	public final java.lang.Boolean getEnable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Enable.toString());
	}

	/**
	 * Set value of Enable
	 * @param enable
	 */
	public final void setEnable(java.lang.Boolean enable)
	{
		setEnable(getContext(), enable);
	}

	/**
	 * Set value of Enable
	 * @param context
	 * @param enable
	 */
	public final void setEnable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enable)
	{
		getMendixObject().setValue(context, MemberNames.Enable.toString(), enable);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AkSk_Group
	 */
	public final dataauth.proxies.Group getAkSk_Group() throws com.mendix.core.CoreException
	{
		return getAkSk_Group(getContext());
	}

	/**
	 * @param context
	 * @return value of AkSk_Group
	 * @throws com.mendix.core.CoreException
	 */
	public final dataauth.proxies.Group getAkSk_Group(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dataauth.proxies.Group result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AkSk_Group.toString());
		if (identifier != null) {
			result = dataauth.proxies.Group.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AkSk_Group
	 * @param aksk_group
	 */
	public final void setAkSk_Group(dataauth.proxies.Group aksk_group)
	{
		setAkSk_Group(getContext(), aksk_group);
	}

	/**
	 * Set value of AkSk_Group
	 * @param context
	 * @param aksk_group
	 */
	public final void setAkSk_Group(com.mendix.systemwideinterfaces.core.IContext context, dataauth.proxies.Group aksk_group)
	{
		if (aksk_group == null) {
			getMendixObject().setValue(context, MemberNames.AkSk_Group.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AkSk_Group.toString(), aksk_group.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return akSkMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dataauth.proxies.AkSk that = (dataauth.proxies.AkSk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
