// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package demo.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Demo module
	public static void addDemo1(IContext context, demo.proxies.DemoEntity _demoEntity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DemoEntity", _demoEntity == null ? null : _demoEntity.getMendixObject());
		Core.microflowCall("Demo.addDemo1").withParams(params).execute(context);
	}
}
