// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package datashare.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import datashare.handler.TableRequestHandlerImpl;

public class TableRequestHandler extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String p;

	public TableRequestHandler(IContext context, java.lang.String p)
	{
		super(context);
		this.p = p;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE

		Core.addRequestHandler(p,new TableRequestHandlerImpl());

		return Boolean.TRUE;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TableRequestHandler";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
